language: c 
python: 
  - "2.7" 
  - "3.5" 
  - "3.6" 
  - "3.7" 

notifications: 
  email: 
    recipients: 
      - giganano9@gmail.com 
    on_success: change 
    on_failure: always 

addons: 
  apt: 
    sources: 
      - ubuntu-toolchain-r-test 
    packages: 
      - gcc-4.8 

matrix: 
  include: 
    - os: osx 
      osx_image: xcode11 
      compiler: clang 
      env: COMPILER=clang 

    - os: osx 
      osx_image: xcode10.2 
      compiler: clang 
      env: COMPILER=clang 

    - os: osx 
      osx_image: xcode9.4 
      compiler: clang 
      env: COMPILER=clang 

    - os: osx 
      osx_image: xcode8.3 
      compiler: clang 
      env: COMPILER=clang 

    - os: linux 
      dist: trusty 
      compiler: gcc 
      env: COMPILER=gcc 

before_install: 
  - pip install Cython --install-option="--no-cython-compile" 
  - python -V 

install: 
  - make 
  - python setup.py install 
  - make clean 

script: 
  - python ./vice/tests/ 

branches: 
  only: 
    - master 

