language: python  
sudo: required 
os: linux 
dist: xenial    # required for python >= 3.7  
python: 
  - 2.7 
  - 3.5 
  - 3.6 
  - 3.7  
env: 
  - COMPILER=gcc 
  - COMPILER=clang 

matrix: 
  fast_finish: true 

notifications: 
  email: 
    recipients: 
      - giganano9@gmail.com 
    on_success: change 
    on_failure: always 

addons: 
  apt: 
    sources: 
      - ubuntu-toolchain-r-test 
    packages: 
      - gcc-4.6 
      - clang-4.2

before_install: 
  - pip install Cython --install-option="--no-cython-compile" 
  - python -V 

install: 
  - make -r CC=$COMPILER 
  - python setup.py install 
  - make clean 

script: 
  - make tests 

branches: 
  only: 
    - master 

