language: python  
sudo: required 
dist: trusty 
python: 
  - "2.7" 
  - "3.5" 
  - "3.6" 
  - "3.7" 
os: 
  - osx 
  - linux 
osx_image: 
  - xcode11 
  - xcode10.2 
  - xcode9.4 
  - xcode8.3 
env: 
  - COMPILER=gcc 
  - COMPILER=clang 

notifications: 
  email: 
    recipients: 
      - giganano9@gmail.com 
    on_success: change 
    on_failure: always 

addons: 
  apt: 
    sources: 
      - ubuntu-toolchain-r-test 
    packages: 
      - gcc-4.8 

matrix: 
  fast_finish: true 
  exclude: 
    - os: osx 
      env: COMPILER=gcc 
    - os: linux 
      env: COMPILER=clang 

before_install: 
  - 
  - pip install Cython --install-option="--no-cython-compile" 
  - python -V 

install: 
  - make -r CC=$COMPILER 
  - python setup.py install 
  - make clean 

script: 
  - echo "test" 

branches: 
  only: 
    - master 

