language: c 

notifications: 
  email: 
    recipients: 
      - giganano9@gmail.com 
    on_success: change 
    on_failure: always 

addons: 
  apt: 
    sources: 
      - ubuntu-toolchain-r-test 
    packages: 
      - gcc-4.8 

matrix: 
  include: 
    - os: osx 
      osx_image: xcode11 
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=2.7 
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: osx 
      osx_image: xcode11
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=3.5 
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: osx 
      osx_image: xcode11
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=3.6 
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: osx 
      osx_image: xcode11 
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=3.7  
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: osx 
      osx_image: xcode10.2 
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=2.7  
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: osx 
      osx_image: xcode10.2
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=3.5 
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: osx 
      osx_image: xcode10.2
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=3.6 
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: osx 
      osx_image: xcode10.2  
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=3.7  
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: osx 
      osx_image: xcode9.4 
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=2.7  
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: osx 
      osx_image: xcode9.4 
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=3.5 
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: osx 
      osx_image: xcode9.4 
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=3.6 
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: osx 
      osx_image: xcode9.4  
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=3.7  
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: osx 
      osx_image: xcode8.3 
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=2.7  
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: osx 
      osx_image: xcode8.3 
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=3.5 
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: osx 
      osx_image: xcode8.3 
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=3.6 
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: osx 
      osx_image: xcode8.3 
      compiler: clang 
      env: COMPILER=clang PYTHON_VERSION=3.7 
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: linux 
      dist: trusty 
      compiler: gcc 
      env: COMPILER=gcc PYTHON_VERSION=2.7 
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: linux 
      dist: trusty 
      compiler: gcc 
      env: COMPILER=gcc PYTHON_VERSION=3.5 
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: linux 
      dist: trusty 
      compiler: gcc 
      env: COMPILER=gcc PYTHON_VERSION=3.6 
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

    - os: linux 
      dist: trusty 
      compiler: gcc 
      env: COMPILER=gcc PYTHON_VERSION=3.7 
      before_install: 
        pip install Cython --install-option="--no-cython-compile"

install: 
  - make -r CC=$COMPILER 
  - python$PYTHON_VERSION setup.py install 
  - make clean 

script: 
  - python$PYTHON_VERSION ./vice/tests/ 

branches: 
  only: 
    - master 

